# Generated by Django 5.1.5 on 2026-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(help_text='Relative URL or absolute path (e.g., /dead-hang/)', max_length=200)),
                ('icon', models.CharField(help_text='Emoji or icon class name (e.g., ⏱️)', max_length=50)),
                ('color', models.CharField(default='#38bdf8', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External App',
                'verbose_name_plural': 'External Apps',
                'ordering': ['order', 'name'],
            },
        ),
    ]
