# Generated by Django 5.2.9 on 2026-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dead_hang', '0002_alter_hangsession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
